import '@/app/globals.css';
import { Providers } from '@/utils/Providers';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next Blog',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50`}>
        <Providers>
          <h1>Navbar</h1>
          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
